NAVBAR
SCWD-nitkkr/sponsy-nitkkr.github.io pull request #22
Opened 2021-12-12 16:33 UTC by navanish07

2021-12-22 05:35 UTC, arpitBhalla requested changes
Make it responsive, make menu overlay on mobile.

2021-12-25 08:07 UTC, mehul-2000 approved these changes
Good design and responsiveness added.

2022-01-09 16:39 UTC, arpitBhalla requested changes

2022-01-09 16:39 UTC, arpitBhalla commented on react/src/styles.css
> +}
Use classNames instead of element Selectors

2022-03-26 19:28 UTC, closed without merging